name: Test

on: [push, pull_request]

# if you push to your branch and it's already running jobs for that branch, it'll kill the old ones
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: install
        run: yarn 

      - name: lint
        run: yarn lint

      - name: lint markdown
        run: yarn lint:markdown

      - name: test
        run: yarn test

      - name: build
        run: yarn build
